import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../widgets/footer/ui/Footer";
import Header from "../widgets/header/ui/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={` ${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col p-6 mx-2">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
